packages:
  - api
  - docs
  - demo/*
  - demo/custom/valaxy-theme-custom
  - packages/*
  - packages/@valaxyjs/*
  - scripts

catalogs:
  build:
    '@iconify-json/ant-design': ^1.2.5
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/logos': ^1.2.9
    '@iconify-json/ri': ^1.2.6
    '@iconify-json/simple-icons': ^1.2.54
    '@iconify-json/vscode-icons': ^1.2.32
    '@intlify/unplugin-vue-i18n': ^11.0.1
    '@unhead/addons': ^2.0.19
    '@unhead/schema-org': ^2.0.19
    '@unhead/vue': ^2.0.19
    consola: ^3.4.2
    typescript: ^5.9.3
    unbuild: ^3.6.1
    unhead: ^2.0.19
    unplugin-vue-router: ^0.16.0
    vite: ^7.1.10
    vue-i18n: ^11.1.12
    zx: ^8.8.4
  frontend:
    '@primevue/themes': ^4.4.1
    primevue: ^4.4.1
    vitepress: ^2.0.0-alpha.12
    vue: ^3.5.22
onlyBuiltDependencies:
  - vue-demi
  - esbuild
